name: CI

on:
  pull_request:
    branches:
      - main


jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build pytest

      - name: build package
        run: python -m build --wheel --outdir dist

      - name: install package
        run: pip install dist/*.whl

      - name: run pytest
        run: pytest tests/

