on:
  push:
    tags:
      - "v*"


jobs:
  build-and-release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - os: windows-latest
            target: x86_64-pc-windows-gnu
          - os: macos-latest
            target: x86_64-apple-darwin

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version:
            - '3.12'
            - '3.11'
            - '3.10'
            - '3.9'

      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install cibuildwheel

      - name: build package
        run: python -m cibuildwheel --output-dir dist

      - name: Publish
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          twine upload dist/*
