on:
  push:
    tags:
      - "v*"


jobs:
  build-and-release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up python
        uses: actions/setup-python@v5

      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build twine

      - name: build package
        run: python -m build --wheel --outdir dist

      - name: Publish
        if: startsWith(github.ref, 'refs/tags/')
        env:
          TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
        run: |
          twine upload dist/*
