on:
  push:
    branches:
      - main
    tags:
      - "v*"


jobs:
  build-and-release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
            # ubuntu
          - os: ubuntu-latest
            python: 39
            platform_id: manylinux_x86_64
          # - os: ubuntu-latest
          #   python: 310
          #   platform_id: manylinux_x86_64
          # - os: ubuntu-latest
          #   python: 311
          #   platform_id: manylinux_x86_64
          # - os: ubuntu-latest
          #   python: 312
          #   platform_id: manylinux_x86_64
            
          #   # windows
          # - os: windows-latest
          #   python: 39
          #   platform_id: win_amd64
          # - os: windows-latest
          #   python: 310
          #   platform_id: win_amd64
          # - os: windows-latest
          #   python: 311
          #   platform_id: win_amd64
          # - os: windows-latest
          #   python: 312
          #   platform_id: win_amd64
            
          #   # macos
          # - os: macos-latest
          #   python: 39
          #   platform_id: macosx_x86_64
          # - os: macos-latest
          #   python: 310
          #   platform_id: macosx_x86_64
          # - os: macos-latest
          #   python: 311
          #   platform_id: macosx_x86_64
          # - os: macos-latest
          #   python: 312
          #   platform_id: macosx_x86_64
            

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up python
        uses: actions/setup-python@v5

      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install cibuildwheel

      - name: build package
        env:
          CIBW_BUILD: "cp${{ matrix.python }}-${{ matrix.platform_id }}"
        run: python -m cibuildwheel --output-dir dist

      - name: Publish
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          twine upload dist/*
